openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: an OpenAPI REST descriptor
paths: {}
components:
  schemas:
    Product:
      type: object
      required:
        - ID
        - name
        - price
      properties:
        ID: &ref_0
          type: number
        name:
          type: string
        price: *ref_0
